_target_: src.datamodules.sn7_datamodule.SpaceNet7Dataset

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 8
train_val_test_split: [0.7, 0.2, 0.1]
num_workers: 8
pin_memory: False

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

expansion_factor: 5
